package com.bookstore.cart.entity;

import com.bookstore.common.entity.BaseEntity;
import com.bookstore.user.entity.User;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.ArrayList;
import java.util.List;

/**
 * Represents the shopping cart belonging to a bookstore user.
 *
 * <p>
 * Each customer has one persistent cart. The cart acts as the
 * aggregate root for the items currently selected by the customer
 * for potential purchase.
 * </p>
 *
 * <p>
 * The cart itself does not store product information. Individual
 * products are represented by {@link CartItem} records associated
 * with this cart.
 * </p>
 *
 * <p>
 * PostgreSQL is the persistent source of truth for the cart while
 * Redis will later be used as a fast-access caching layer.
 * </p>
 */
@Entity
@Table(name = "carts")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Cart extends BaseEntity {

    /**
     * User who owns this shopping cart.
     *
     * <p>
     * Each user can have exactly one cart. The unique constraint
     * generated by the one-to-one relationship prevents multiple
     * carts from being associated with the same user.
     * </p>
     */
    @OneToOne(
            fetch = FetchType.LAZY,
            optional = false
    )
    @JoinColumn(
            name = "user_id",
            nullable = false,
            unique = true
    )
    private User user;

    /**
     * Items currently contained in the shopping cart.
     *
     * <p>
     * Cart items are lifecycle-dependent on the cart. When a cart
     * item is removed from the collection, orphan removal allows
     * the corresponding database record to be removed as well.
     * </p>
     */
    @OneToMany(
            mappedBy = "cart",
            cascade = CascadeType.ALL,
            orphanRemoval = true,
            fetch = FetchType.LAZY
    )
    @Builder.Default
    private List<CartItem> items = new ArrayList<>();
}