package com.bookstore.audit.entity;

import com.bookstore.common.entity.BaseEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.UUID;

/**
 * Represents a persistent audit record generated by the application.
 *
 * <p>
 * Audit logs provide a historical record of important application
 * operations, including the action performed, affected entity,
 * authenticated user, request information, execution status,
 * and execution time.
 * </p>
 */
@Entity
@Table(name = "audit_logs")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AuditLog extends BaseEntity {

    /**
     * Business action that was performed.
     *
     * <p>
     * Examples:
     * CREATE_BOOK, UPDATE_BOOK, DELETE_BOOK,
     * UPDATE_INVENTORY, CREATE_ORDER.
     * </p>
     */
    @Column(name = "action", nullable = false, length = 100)
    private String action;

    /**
     * Type of entity affected by the operation.
     *
     * <p>
     * Examples: BOOK, USER, INVENTORY, ORDER.
     * </p>
     */
    @Column(name = "entity", nullable = false, length = 100)
    private String entity;

    /**
     * Identifier of the affected entity.
     */
    @Column(name = "entity_id")
    private UUID entityId;

    /**
     * Username or email of the authenticated user
     * who performed the operation.
     */
    @Column(name = "username", length = 255)
    private String username;

    /**
     * HTTP method associated with the operation.
     */
    @Column(name = "http_method", length = 20)
    private String httpMethod;

    /**
     * Request URI associated with the operation.
     */
    @Column(name = "request_uri", length = 1000)
    private String requestUri;

    /**
     * IP address from which the request originated.
     */
    @Column(name = "ip_address", length = 100)
    private String ipAddress;

    /**
     * Indicates whether the operation completed successfully.
     */
    @Column(name = "success", nullable = false)
    private boolean success;

    /**
     * Exception type when the operation fails.
     */
    @Column(name = "exception_type", length = 255)
    private String exceptionType;

    /**
     * Error message when the operation fails.
     */
    @Column(name = "error_message", columnDefinition = "TEXT")
    private String errorMessage;

    /**
     * Execution time of the intercepted operation in milliseconds.
     */
    @Column(name = "execution_time_ms")
    private Long executionTimeMs;
}